### ISSUE TITLE
Error on Display Owner

### ISSUE THREAD

**Issue by yipson** [yipson/pet-clinic#63]

**Comment by yipson** [comment]
Caused by: org.attoparser.ParseException: Exception evaluating SpringEL expression: "#temporals.format(pet.birthDate, 'yyyy-MM-dd')" (template: "owners/ownerDetails" - line 50, col 25)
	at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:393) ~[attoparser-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.attoparser.MarkupParser.parse(MarkupParser.java:257) ~[attoparser-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:230) ~[thymeleaf-3.0.12.RELEASE.jar:3.0.12.RELEASE]
	... 55 common frames omitted
